apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: task-events-subscription
spec:
  topic: task-events
  routes:
    default: /events/task
  pubsubname: taskpubsub
  deadLetterTopic: dead-letter-queue
