apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: taskpubsub
spec:
  type: pubsub.kafka
  version: v1
  metadata:
    - name: brokers
      value: "kafka:9092"
    - name: consumerGroup
      value: "reminder-service"
    - name: clientID
      value: "reminder-service"
    - name: authType
      value: "none"
    - name: maxMessageBytes
      value: "1048576"
